#VOL_INSTALL=/Users/junmin/mywork/ECP-HDF5-VOL/install/usr/local/HDF_Group/HDF5/1.11.0/
#VOL_INSTALL=/Users/junmin/mywork/ECP-HDF5-VOL/install_mpi/usr/local/HDF_Group/HDF5/1.9.234/
VOL_INSTALL=//Users/junmin/software/HDF5/dev/install/usr/local/HDF_Group/HDF5/1.11.4/

# vol src is needed for H5ESpublic.h
#VOL_SRC_INCLUDE=/Users/junmin/mywork/ECP-HDF5-VOL/hdf5/src 
VOL_SRC_INCLUDE=/Users/junmin/software/HDF5/dev/hdf5/src/

CC=/Library/Developer/CommandLineTools/usr/bin/cc 
LIBTOOL=/Library/Developer/CommandLineTools/usr/bin/libtool
TARGET=adios_vol_mpi

CFLAGS=-I${VOL_SRC_INCLUDE} -I. 
OBJ=adios_vol.o main.o reader.o util.o hyperMap.o
PLUGIN_LIBOBJS=adios_vol.o reader.o util.o hyperMap.o
#LIBS=${VOL_INSTALL}/lib/libhdf5-static.a -lm -ldl /usr/local/Cellar/mpich/3.2_3/lib/libmpi.dylib  
LIBS=${VOL_INSTALL}/lib/libhdf5_debug.a	-lm -ldl /usr/local/Cellar/mpich/3.2_3/lib/libmpi.dylib  
%.o: %.c 
	$(CC) -g -c -o $@ $< $(CFLAGS)
adios_vol_mpi:  ${OBJ}
	${CC} -g -o $@ $^  ${LIBS}
clean :
	rm ${TARGET} *.o

#libtool -static   -o libAdiosVol.a  adios_vol.o hyperMap.o reader.o util.o
libAdiosVol.a: ${PLUGIN_LIBOBJS}
	${LIBTOOL} -static -o $@ $^ 

all: adios_vol_mpi libAdiosVol.a